export { default as HomePage } from './HomePage'
export { default as TestPage } from './TestPage'
export { default as NotFoundPage } from './NotFoundPage'
export { default as LoginPage } from './LoginPage'
export { default as SignupPage } from './SignupPage'
